### Tiffin's Github.io Site

theme: jekyll-theme-hacker
title: Tiffin''s Github.io Site
description: Journey to Web Development

highlighter: rouge
markdown: kramdown

# Social media links in footer
facebook: "https://www.facebook.com/tiffin"
twitter: "https://www.twitter.com/tiggertiffin87"
linkedin: "https://www.linkedin.com/in/tiffin"
github: "https://www.github.com/tiffin-filion"

highlighter: rouge
markdown: kramdown

#collection
collections:
projects:
output: true
permalink: /projects/:path/

sass:
sass_dir: /assets/css/_sass

include:
- _pages

exclude:
- README.md
- LICENSE.md

plugins:
- jekyll-target-blank
