### Tiffin's Github.io Site

title: Tiffin's Github.io Site
description: Journey to Web Development

baseurl:  #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: hello@tiffinity.co #email address

highlighter: rouge
markdown: kramdown

# Social media links in footer
facebook: "tiffin"
twitter: "tiggertiffin87"
linkedin: "tiffin"
github: "tiffin-filion"

highlighter: rouge
markdown: kramdown

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
