### Tiffin's Github.io Site

title: Tiffin's Github.io Site
description: Journey to Web Development

highlighter: rouge
markdown: kramdown

# Social media links in footer
facebook: "tiffin.filion"
linkedin: "tiffin"
github: "tiffin-filion"

#collection
collections:
  projects:
    output: true

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
